import manifest from './generated-manifest.json';

// Regenerated by scripts/generate-manifest.js (runs on predev/prebuild) from
// ffprobe readings of the real files in public/. If the script can't run
// (no public/ media or no ffprobe, e.g. on CI), the committed JSON is used.

interface MediaEntry {
  durationSec: number;
  durationMs: number;
  sizeBytes: number;
}

const audio = manifest.audio as Record<string, MediaEntry>;
const video = manifest.video as Record<string, MediaEntry>;
const patterns = manifest.patterns as Record<string, { totalDurationMs: number; totalDurationSec: number }>;

// Safety net if a pattern's bed track is missing from the manifest.
const FALLBACK_DURATION_MS: Record<string, number> = {
  resonance:    20 * 60 * 1000,
  box:          10 * 60 * 1000,
  sleep:        30 * 60 * 1000,
  tirumandiram: 30 * 60 * 1000,
};

/** Exact session length for a pattern, straight from its bed track's ffprobe duration. */
export const getPatternDurationMs = (patternId: string): number => {
  const exact = patterns[patternId]?.totalDurationMs;
  if (exact && exact > 0) return exact;
  console.warn(`assetManifest: no measured duration for pattern "${patternId}" — using fallback`);
  return FALLBACK_DURATION_MS[patternId] ?? 30 * 60 * 1000;
};

/** Exact duration of an audio file in public/audio (by filename), or null if unknown. */
export const getAudioDurationMs = (filename: string): number | null =>
  audio[filename]?.durationMs ?? null;

/** Exact duration of a video file in public/video (by filename), or null if unknown. */
export const getVideoDurationMs = (filename: string): number | null =>
  video[filename]?.durationMs ?? null;

export { manifest };
